### ISSUE TITLE
Skill Master Repository

### ISSUE THREAD

**Issue by TonyHfict** [oguzCoel/skillmanager#12]
Klasse Skill Master Repository Testen mit JUnit

**Comment by TonyHfict** [comment]
Test erfolgreich Durchgeführt Test Dokument under
https://drive.google.com/drive/u/1/folders/0B9kZ0CfsNnU3fkszVlR6VEszUFJmckFlT2h4OEExYzJfRFkzWUFILVVzT2lYbFd3T1RwZ28

SkillMasterRepositorytest.docx

**Comment by oguzCoel** [comment]
Vorgesehene Zeit gestern (04.07.2015) abgelaufen. Ticket wird geschlossen.
