### ISSUE TITLE
Task Repository

### ISSUE THREAD

**Issue by TonyHfict** [oguzCoel/skillmanager#14]
Klasse Task Repository Testen mit JUnit

**Comment by oguzCoel** [comment]
Hallo Tony dieser Repository wird keine Daten liefern, da wir nicht zu Erfassung der Task  gekommen sind. Daher macht hier ein Unit Test kein Sinn

**Comment by oguzCoel** [comment]
Vorgesehene Zeit gestern (04.07.2015) abgelaufen. Ticket wird geschlossen.
