### ISSUE TITLE
Cobertura einbinden in das Projekt

### ISSUE THREAD

**Issue by TonyHfict** [oguzCoel/skillmanager#22]
Um Messungen zu machen die Auskunft geben über den Abdeckung grad  mit Test
wird Cobertura eingesetzt

**Comment by TonyHfict** [comment]
http://www.mkyong.com/qa/maven-cobertura-code-coverage-example/
Beschreibung wie mit Maven einbinden

**Comment by oguzCoel** [comment]
Vorgesehene Zeit gestern(04.07.2015) abgelaufen. Ticket wird geschlossen
