### ISSUE TITLE
Test BenuterRepository mit JUnit

### ISSUE THREAD

**Issue by TonyHfict** [oguzCoel/skillmanager#5]
Die Klasse BenutzerRepository wird mit JUnit getestet

**Comment by TonyHfict** [comment]
Test Protokoll wurde erstellt.
BenutzerRepositorytest.docx abrufbar unter 
https://drive.google.com/drive/u/1/folders/0B9kZ0CfsNnU3fkszVlR6VEszUFJmckFlT2h4OEExYzJfRFkzWUFILVVzT2lYbFd3T1RwZ28

**Comment by oguzCoel** [comment]
Hallo Tony,

ist das Ticket erledigt ? Falls ja, musst du es dir zuweisen und schliessen.

**Comment by oguzCoel** [comment]
Habe noch ein Label fürs Testing erstellt.
